# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52f35482b90081d2ac3f343ff24022e0e3340e4dedd05432707e1cefd2334dace3eca82c51bc15b2ba52135c1544a798cef9103ff738d597eae8f004715439ff

test:
  secret_key_base: e44b4f77b1dc25463d9eaaba16f024cc811b9a5ccd9fe4600ce932fb225dfcaf795e0ff224f86bd07cfc6e687254017f4297e55a88a29bcde4dde19e1a9d7235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
